site_name: FPLstat
site_description: Python package for loading and transforming data from the Fantasy Premier League API
site_url: https://james-leslie.github.io/fplstat/
repo_url: https://github.com/James-Leslie/fplstat
repo_name: James-Leslie/fplstat

theme:
    name: material
    features:
        - content.code.annotate
        - content.code.copy
        - content.footnote.tooltips
        - content.tabs.link
        - content.tooltips
        - navigation.footer
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    logo: img/futbol-regular-full-white.svg
    favicon: img/futbol-regular-full.svg

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink
extra:
  external_links:
    target: _blank
    rel: noopener noreferrer

plugins:
    - search
    # https://mkdocstrings.github.io/
    - mkdocstrings:
        default_handler: python
        locale: en
        handlers:
          python:
            options:
                docstring_style: google
                extensions:
                - griffe_typingdoc
                ignore_init_summary: false
                members_order: source
                show_root_heading: true
                show_if_no_docstring: true
                separate_signature: true
                unwrap_annotated: true
                merge_init_into_class: true
                signature_crossrefs: true
                show_symbol_type_heading: true
                show_symbol_type_toc: true
                show_source: false
                show_signature_annotations: true
                summary:
                    functions: true
    # https://github.com/danielfrg/mkdocs-jupyter
    - mkdocs-jupyter:
        ignore_h1_titles: True
        include: ["examples/*.ipynb"]
        execute: true

nav:
    - FPLstat: index.md
    - Getting started: getting_started.md
    - Examples:
        - Quickstart: examples/0_quickstart.ipynb
    - Reference:
        - reference/api.md